# NoSwiper illumos Configuration
# This file is embedded at compile time and provides the default rules for illumos distributions
# Users can override these with ~/.config/noswiper/config.yaml

# Default base paths for Solaris/illumos
default_base_paths:
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/bin
  - /usr/local/sbin
  - /opt/csw/bin # OpenCSW packages
  - /opt/csw/sbin
  - /opt/local/bin # SmartOS pkgsrc
  - /opt/local/sbin
  - /usr/gnu/bin # GNU utilities on Solaris
  - /usr/xpg4/bin # POSIX utilities
  - /usr/xpg6/bin # POSIX utilities
  - /usr/sfw/bin # Sun Freeware
  - /usr/sfw/sbin
  - /usr/ucb # BSD compatibility
