# NoSwiper Solaris/illumos Configuration
# This file is embedded at compile time and provides the default rules for Solaris/illumos
# Users can override these with ~/.config/noswiper/config.yaml

# Global exclusions - processes that can access ANY protected file
# IMPORTANT: Every global exclusion MUST have a hardcoded path
#   - Additional restrictions like base and ppid are recommended
# Without path, a rule could match any process!
global_exclusions:
  - base: "ufsdump" # Solaris backup utility
    path: "/usr/sbin/ufsdump"

# Default base paths for Solaris/illumos
default_base_paths:
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/bin
  - /usr/local/sbin
  - /opt/csw/bin # OpenCSW packages
  - /opt/csw/sbin
  - /opt/local/bin # SmartOS pkgsrc
  - /opt/local/sbin
  - /usr/gnu/bin # GNU utilities on Solaris
  - /usr/xpg4/bin # POSIX utilities
  - /usr/xpg6/bin # POSIX utilities
  - /usr/sfw/bin # Sun Freeware
  - /usr/sfw/sbin
  - /usr/ucb # BSD compatibility
