# NoSwiper FreeBSD Configuration
# This file is embedded at compile time and provides the default rules for FreeBSD
# Users can override these with ~/.config/noswiper/config.yaml

# Global exclusions - processes that can access ANY protected file
# IMPORTANT: Every global exclusion MUST have a hardcoded path
#   - Additional restrictions like base and ppid are recommended
# Without path, a rule could match any process!
global_exclusions:
  - base: "tarsnap" # Popular on FreeBSD
    path: "/usr/local/bin/tarsnap"
  - base: "dump" # FreeBSD backup utility
    path: "/sbin/dump"
  - base: "restore"
    path: "/sbin/restore"
  - base: "duplicity"
    path: "/usr/local/bin/duplicity"
  - base: "borg"
    path: "/usr/local/bin/borg"
  - base: "restic"
    path: "/usr/local/bin/restic"
  - base: "syncthing"
    path: "/usr/local/bin/syncthing"

# Default base paths for FreeBSD
default_base_paths:
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/bin
  - /usr/local/sbin
  - ~/.local/bin
  - /usr/local/libexec
