# NoSwiper NetBSD Configuration
# This file is embedded at compile time and provides the default rules for NetBSD
# Users can override these with ~/.config/noswiper/config.yaml

# Global exclusions - processes that can access ANY protected file
# IMPORTANT: Every global exclusion MUST have a hardcoded path_pattern
#   - Additional restrictions like base and ppid are recommended
# Without path_pattern, a rule could match any process!
global_exclusions:
  # Backup programs
  - base: "rsync"
    path_pattern: "/usr/pkg/bin/rsync"
  - base: "rsyncd"
    path_pattern: "/usr/pkg/*bin/rsyncd"
  - base: "dump"  # NetBSD backup utility
    path_pattern: "/sbin/dump"
  - base: "restore"
    path_pattern: "/sbin/restore"
  - base: "pax"  # NetBSD archiver
    path_pattern: "/bin/pax"
  - base: "duplicity"
    path_pattern: "/usr/pkg/bin/duplicity"
  - base: "borg"
    path_pattern: "/usr/pkg/bin/borg"

  # Cloud sync services
  - base: "syncthing"
    path_pattern: "/usr/pkg/bin/syncthing"
    ppid: 1
  - base: "rclone"
    path_pattern: "/usr/pkg/bin/rclone"

# Files and patterns to protect
protected_files:
  # SSH Keys and Known Hosts
  - id: ssh_keys
    patterns:
      - "~/.ssh/id_*"
      - "~/.ssh/*_key"
    allow:
      # SSH tools
      - base: "ssh"
      - base: "ssh-add"
      - base: "ssh-agent"
      - base: "ssh-keygen"
      - base: "scp"
      - base: "sftp"
      - base: "sshd"
      - base: "git"
      - base: "rsync"

  # SSH Known Hosts (used for lateral movement/reconnaissance)
  - id: ssh_known_hosts
    pattern: "~/.ssh/known_hosts"
    allow:
      # SSH tools
      - base: "ssh"
      - base: "ssh-keygen"
      - base: "ssh-keyscan"
      # Git (updates known_hosts when cloning)
      - base: "git"
      # rsync over SSH
      - base: "rsync"
      # Zsh (reads known_hosts for tab completion)
      - base: "zsh"

  # AWS Credentials
  - id: aws_credentials
    patterns:
      - "~/.aws/credentials"
      - "~/.aws/config"
    allow:
      - base: "aws"
        path_pattern: "/usr/pkg/bin/aws"
      - base: "terraform"
        path_pattern: "/usr/pkg/bin/terraform"
      - base: "ansible"
        path_pattern: "/usr/pkg/bin/ansible*"
      - base: "ansible-playbook"
        path_pattern: "/usr/pkg/bin/ansible-playbook"
      - base: "packer"
        path_pattern: "/usr/pkg/bin/packer"
      # Python for boto3
      - base: "python*"
        path_pattern: "/usr/pkg/bin/python*"
      - base: "python3"
        path_pattern: "~/.venv/*/bin/*"

  # Google Cloud
  - id: gcloud_credentials
    patterns:
      - "~/.config/gcloud/credentials.db"
      - "~/.config/gcloud/access_tokens.db"
    allow:
      - base: "gcloud"
        path_pattern: "/usr/pkg/bin/gcloud"
      - base: "gsutil"
      - base: "bq"
      - base: "kubectl"
        path_pattern: "/usr/pkg/bin/kubectl"
      - base: "python*"
        path_pattern: "/usr/pkg/bin/python*"

  # Azure
  - id: azure_credentials
    patterns:
      - "~/.azure/accessTokens.json"
    allow:
      - base: "az"
        path_pattern: "/usr/pkg/bin/az"
      - base: "azure-cli"

  # GPG Keys
  - id: gpg_keys
    patterns:
      - "~/.gnupg/private-keys*"
      - "~/.gnupg/secring.gpg"
    allow:
      - base: "gpg"
      - base: "gpg2"
      - base: "gpg-agent"
      - base: "pinentry*"
      - base: "pass"
        path_pattern: "/usr/pkg/bin/pass"

  # Package Manager Credentials
  - id: npm_credentials
    patterns:
      - "~/.npmrc"
    allow:
      - base: "npm"
        path_pattern: "/usr/pkg/bin/npm"
      - base: "node"
        path_pattern: "/usr/pkg/bin/node"
      - base: "yarn"
        path_pattern: "/usr/pkg/bin/yarn"

  - id: python_credentials
    patterns:
      - "~/.pypirc"
    allow:
      - base: "python*"
        path_pattern: "/usr/pkg/bin/python*"
      - base: "pip*"
        path_pattern: "/usr/pkg/bin/pip*"
      - base: "easy_install*"
        path_pattern: "/usr/pkg/bin/easy_install*"
      - base: "poetry"
      - base: "twine"

  - id: cargo_credentials
    patterns:
      - "~/.cargo/credentials"
    allow:
      - base: "cargo"
        path_pattern: "~/.cargo/bin/cargo"
      - base: "rustc"
        path_pattern: "~/.cargo/bin/rustc"
      - base: "rustup"
        path_pattern: "~/.cargo/bin/rustup"

  # Docker
  - id: docker_credentials
    patterns:
      - "~/.docker/config.json"
    allow:
      - base: "docker"
        path_pattern: "/usr/pkg/bin/docker"
      - base: "docker-compose"
        path_pattern: "/usr/pkg/bin/docker-compose"

  # Kubernetes
  - id: kubernetes_config
    patterns:
      - "~/.kube/config"
    allow:
      - base: "kubectl"
        path_pattern: "/usr/pkg/bin/kubectl"
      - base: "helm"
        path_pattern: "/usr/pkg/bin/helm"
      - base: "k9s"
        path_pattern: "/usr/pkg/bin/k9s"

  # Browser Password Stores - Firefox
  - id: firefox_passwords
    patterns:
      - "~/.mozilla/firefox/*/logins.json"
      - "~/.mozilla/firefox/*/key*.db"
      - "~/.mozilla/firefox/*/cookies.sqlite"
    allow:
      - base: "firefox"
        path_pattern: "/usr/pkg/bin/firefox"
        ppid: 1
      - base: "firefox-esr"
        path_pattern: "/usr/pkg/bin/firefox-esr"
        ppid: 1

  # Chromium
  - id: chromium_passwords
    patterns:
      - "~/.config/chromium/*/Login Data"
      - "~/.config/chromium/*/Cookies"
      - "~/.config/chromium/*/Web Data"
    allow:
      - base: "chromium"
        path_pattern: "/usr/pkg/bin/chromium"
        ppid: 1

  # Password Managers
  - pattern: "~/.password-store/**/*.gpg"
    allow:
      - base: "pass"
        path_pattern: "/usr/pkg/bin/pass"
      - base: "gpg"
      - base: "gpg2"

  - pattern: "~/.config/keepassxc/*.kdbx"
    allow:
      - base: "keepassxc"
        path_pattern: "/usr/pkg/bin/keepassxc"
        ppid: 1

  # Email Clients
  - pattern: "~/.thunderbird/*/logins.json"
    allow:
      - base: "thunderbird"
        path_pattern: "/usr/pkg/bin/thunderbird"
        ppid: 1

  - pattern: "~/.claws-mail/accountrc"
    allow:
      - base: "claws-mail"
        path_pattern: "/usr/pkg/bin/claws-mail"
        ppid: 1

  # Development Tools
  - pattern: "~/.config/filezilla/sitemanager.xml"
    allow:
      - base: "filezilla"
        path_pattern: "/usr/pkg/bin/filezilla"
        ppid: 1

  # VPN Configurations
  - id: vpn_configs
    patterns:
      - "~/.config/openvpn/*"
      - "/usr/pkg/etc/openvpn/*"
    allow:
      - base: "openvpn"
        path_pattern: "/usr/pkg/sbin/openvpn"

  # Shell History Files
  - id: shell_history
    patterns:
      - "~/.bash_history"
      - "~/.zsh_history"
      - "~/.history"  # ksh/sh
      - "~/.local/share/fish/fish_history"
    allow:
      # Only shells themselves should read/write their history
      - base: "bash"
      - base: "zsh"
      - base: "fish"
      - base: "sh"
      - base: "ksh"  # Korn shell
      - base: "csh"
      - base: "tcsh"

  # NetBSD pkgsrc database
  - pattern: "/var/db/pkg/*"
    allow:
      - base: "pkg_*"  # pkg_add, pkg_delete, etc.
        path_pattern: "/usr/sbin/pkg_*"
      - base: "pkgin"
        path_pattern: "/usr/pkg/bin/pkgin"

# Patterns to exclude from monitoring (not sensitive)
excluded_patterns:
  - "*.pub"               # Public keys
  - "*.pem"              # Often certificates (though could be private keys)
  - "authorized_keys"     # SSH authorized keys file

# Default base paths for NetBSD
default_base_paths:
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/pkg/bin  # NetBSD pkgsrc packages install here
  - /usr/pkg/sbin
  - /usr/pkg/libexec
  - /usr/X11R7/bin  # X11 binaries
  - ~/.local/bin

# Monitoring configuration
monitoring:
  buffer_size: 1000
  max_events_per_sec: 100