# NoSwiper Solaris/illumos Configuration
# This file is embedded at compile time and provides the default rules for Solaris/illumos
# Users can override these with ~/.config/noswiper/config.yaml

# Global exclusions - processes that can access ANY protected file
# IMPORTANT: Every global exclusion MUST have a hardcoded path_pattern
#   - Additional restrictions like base and ppid are recommended
# Without path_pattern, a rule could match any process!
global_exclusions:
  # Backup programs
  - base: "rsync"
    path_pattern: "/usr/bin/rsync"
  - base: "rsyncd"
    path_pattern: "/usr/*bin/rsyncd"
  - base: "tar"
    path_pattern: "/usr/*bin/tar"
  - base: "gtar"  # GNU tar
    path_pattern: "/usr/*bin/gtar"
  - base: "ufsdump"  # Solaris backup utility
    path_pattern: "/usr/sbin/ufsdump"
  - base: "zfs"  # ZFS commands may need access for send/recv
    path_pattern: "/usr/sbin/zfs"

# Files and patterns to protect
protected_files:
  # SSH Keys
  - id: ssh_keys
    patterns:
      - "~/.ssh/id_*"
      - "~/.ssh/*_key"
    allow:
      # SSH tools
      - base: "ssh"
      - base: "ssh-add"
      - base: "ssh-agent"
      - base: "ssh-keygen"
      - base: "scp"
      - base: "sftp"
      - base: "sshd"
        path_pattern: "/usr/lib/ssh/sshd"  # Solaris sshd location
      - base: "git"
      - base: "rsync"

  # SSH Known Hosts (used for lateral movement/reconnaissance)
  - id: ssh_known_hosts
    pattern: "~/.ssh/known_hosts"
    allow:
      # SSH tools that actually read/write known_hosts
      - base: "ssh"
      - base: "ssh-keygen"
      - base: "ssh-keyscan"
      - base: "scp"
      - base: "sftp"
      # Git (updates known_hosts when cloning)
      - base: "git"
      # rsync over SSH
      - base: "rsync"
      # Zsh (reads known_hosts for tab completion)
      - base: "zsh"

  # AWS Credentials
  - id: aws_credentials
    patterns:
      - "~/.aws/credentials"
      - "~/.aws/config"
    allow:
      - base: "aws"
      - base: "terraform"
      - base: "ansible"
      - base: "ansible-playbook"
      - base: "packer"
      # Python for boto3
      - base: "python"
        path_pattern: "/usr/bin/python*"
      - base: "python3"
        path_pattern: "/usr/bin/python3*"
      - base: "python"
        path_pattern: "/opt/csw/bin/python*"  # OpenCSW packages
      - base: "python3"
        path_pattern: "~/.venv/*/bin/*"

  # Google Cloud
  - id: gcloud_credentials
    patterns:
      - "~/.config/gcloud/credentials.db"
      - "~/.config/gcloud/access_tokens.db"
    allow:
      - base: "gcloud"
      - base: "gsutil"
      - base: "bq"
      - base: "kubectl"
      - base: "python"
      - base: "python3"

  # Azure
  - id: azure_credentials
    patterns:
      - "~/.azure/accessTokens.json"
    allow:
      - base: "az"
      - base: "azure-cli"

  # GPG Keys
  - id: gpg_keys
    patterns:
      - "~/.gnupg/private-keys*"
      - "~/.gnupg/secring.gpg"
    allow:
      - base: "gpg"
      - base: "gpg2"
      - base: "gpg-agent"
      - base: "pinentry*"
      - base: "pass"

  # Package Manager Credentials
  - id: npm_credentials
    patterns:
      - "~/.npmrc"
    allow:
      - base: "npm"
        path_pattern: "/opt/local/bin/npm"  # SmartOS pkgsrc
      - base: "npm"
        path_pattern: "/usr/bin/npm"
      - base: "node"
      - base: "yarn"

  - id: python_credentials
    patterns:
      - "~/.pypirc"
    allow:
      - base: "python"
      - base: "python3"
      - base: "pip"
      - base: "pip3"
      - base: "easy_install"

  - id: cargo_credentials
    patterns:
      - "~/.cargo/credentials"
    allow:
      - base: "cargo"
      - base: "rustc"
      - base: "rustup"

  # Docker/Zones
  - id: docker_credentials
    patterns:
      - "~/.docker/config.json"
    allow:
      - base: "docker"
      - base: "docker-compose"

  # Kubernetes
  - id: kubernetes_config
    patterns:
      - "~/.kube/config"
    allow:
      - base: "kubectl"
      - base: "helm"
      - base: "k9s"

  # Browser Password Stores - Firefox
  - id: firefox_passwords
    patterns:
      - "~/.mozilla/firefox/*/logins.json"
      - "~/.mozilla/firefox/*/key*.db"
      - "~/.mozilla/firefox/*/cookies.sqlite"
    allow:
      - base: "firefox"
        ppid: 1
      - base: "firefox-bin"
        ppid: 1

  # Oracle Database Credentials
  - id: oracle_wallet
    patterns:
      - "~/oracle/wallet/*"
      - "~/.oracle/wallet/*"
      - "$ORACLE_HOME/network/admin/*.ora"
    allow:
      - base: "sqlplus"
        path_pattern: "$ORACLE_HOME/bin/sqlplus"
      - base: "tnsping"
        path_pattern: "$ORACLE_HOME/bin/tnsping"
      - base: "oracle"
        path_pattern: "$ORACLE_HOME/bin/*"

  # Oracle Cloud Infrastructure CLI
  - id: oci_config
    patterns:
      - "~/.oci/config"
      - "~/.oci/*.pem"
    allow:
      - base: "oci"
      - base: "oci-cli"

  # Password Managers
  - pattern: "~/.password-store/**/*.gpg"
    allow:
      - base: "pass"
      - base: "gpg"
      - base: "gpg2"

  # Email Clients
  - pattern: "~/.thunderbird/*/logins.json"
    allow:
      - base: "thunderbird"
        ppid: 1

  # Development Tools
  - pattern: "~/.config/filezilla/sitemanager.xml"
    allow:
      - base: "filezilla"
        ppid: 1

  - pattern: "~/.config/filezilla/recentservers.xml"
    allow:
      - base: "filezilla"
        ppid: 1

  # VPN Configurations
  - id: vpn_configs
    patterns:
      - "~/.config/openvpn/*"
      - "/etc/inet/ike/config/*"  # Solaris IKE configs
    allow:
      - base: "openvpn"
      - base: "in.iked"  # Solaris IKE daemon
        path_pattern: "/usr/lib/inet/in.iked"

  # Shell History Files
  - id: shell_history
    patterns:
      - "~/.bash_history"
      - "~/.zsh_history"
      - "~/.sh_history"
      - "~/.history"  # ksh history
    allow:
      # Only shells themselves should read/write their history
      - base: "bash"
      - base: "zsh"
      - base: "ksh"  # Korn shell (default on Solaris)
      - base: "ksh93"
      - base: "sh"
      - base: "tcsh"
      - base: "csh"

  # SMF Service Credentials (Solaris Service Management Facility)
  - pattern: "/etc/svc/volatile/*"
    allow:
      - base: "svc.configd"
        path_pattern: "/lib/svc/bin/svc.configd"
      - base: "svc.startd"
        path_pattern: "/lib/svc/bin/svc.startd"
      - base: "svccfg"
        path_pattern: "/usr/sbin/svccfg"
      - base: "svcadm"
        path_pattern: "/usr/sbin/svcadm"

# Patterns to exclude from monitoring (not sensitive)
excluded_patterns:
  - "*.pub"               # Public keys
  - "*.pem"              # Often certificates (though could be private keys)
  - "authorized_keys"     # SSH authorized keys file

# Default base paths for Solaris/illumos
default_base_paths:
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/bin
  - /usr/local/sbin
  - /opt/csw/bin  # OpenCSW packages
  - /opt/csw/sbin
  - /opt/local/bin  # SmartOS pkgsrc
  - /opt/local/sbin
  - /usr/gnu/bin  # GNU utilities on Solaris
  - /usr/xpg4/bin  # POSIX utilities
  - /usr/xpg6/bin  # POSIX utilities
  - /usr/sfw/bin  # Sun Freeware
  - /usr/sfw/sbin
  - /usr/ucb  # BSD compatibility

# Monitoring configuration
monitoring:
  buffer_size: 1000
  max_events_per_sec: 100